### ISSUE TITLE
Collision code crash only in debug mode

### ISSUE THREAD

**Issue by michael-fadely** [SonicFreak94/sadx-limit-break#1]
Happens primarily when collecting a minimal.

**Comment by SonicFreak94** [comment]
hello bot maybe

**Comment by michael-fadely** [comment]
Looks like this is caused in part by the custom object allocator. Disabling it fixes the issue (and more specifically, commenting the `delete` at the end of the deletion function), so it's probably safe to say that the game is trying to access an object that's already been deallocated. It might be worth it to re-implement a system more similar to the original code, but in a dynamically expanding array that won't re-allocate any of its data (i.e not `vector`).

...but why only in the debug build?
(note for me: `NaiZoGola`)
